version: '3'

services:

  ruby:
    container_name: rb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - FM_HOME=app
      - START_DOCKER=true
      - LC_ALL=pt_BR.UTF-8