version: '3'

services:

  ruby:
    container_name: ruby
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:4567
    volumes:
      - .:/app
      - gems:/usr/local/bundle

volumes:
  gems: